type LangStringsType = {
  [language: string]: {
    [word: string]: string;
  };
};

export const LangStrings: LangStringsType = {
  pt: {
    clickHere: 'Clique aqui',
    confirmation: 'Tem certeza que deseja remover esta pergunta?',
    createARoom: 'Criar uma nova sala',
    createRoom: 'Criar sala',
    deleteQuestion: 'Excluir pergunta',
    enter: 'Entrar na sala',
    gbutton: 'Crie sua sala com o Google',
    highlight: 'Destacar',
    homesub: 'Tire dúvidas de sua audiência em tempo real',
    hometitle: 'Crie salas de Q&A ao vivo',
    illustration: 'Ilustração: perguntas e respostas',
    markAnswered: 'Marcar como respondida',
    markLike: 'Marcar como gostei',
    newRoomPhrase: 'Quer entrar em uma sala existente?',
    question: 'pergunta',
    questionInstruction: 'Para enviar uma pergunta',
    questionPhrase: 'O que deseja perguntar?',
    room: 'Sala',
    roomClose: 'Encerrar sala',
    roomInput: 'Digite o código da sala',
    roomName: 'Nome da sala',
    send: 'Enviar',
    separator: 'ou entre em uma sala',
    signIn: 'faça seu login',
  },
  en: {
    clickHere: 'Click here',
    confirmation: 'Are you sure you wish to remove this question?',
    createARoom: 'Create a new room',
    createRoom: 'Create room',
    deleteQuestion: 'Delete question',
    enter: 'Enter room',
    gbutton: 'Create a new room with Google',
    highlight: 'Highlight',
    homesub: 'Clear doubts of your audience in real time',
    hometitle: 'Create live Q&A rooms',
    illustration: 'Ilustration: question and answers',
    markAnswered: 'Mark as answered',
    markLike: 'Mark as liked',
    newRoomPhrase: 'Want to enter another room?',
    question: 'question',
    questionInstruction: 'To make a question',
    questionPhrase: 'What do you want to ask?',
    room: 'Room',
    roomClose: 'Close room',
    roomInput: 'Write the room code',
    roomName: 'Room name',
    send: 'Send',
    separator: 'or enter a room',
    signIn: 'sign in',
  },
};
